### PR TITLE
ervaibhavkumar Adding code for Binary Search in Python

### PR DESCRIPTION
**Pull request by ervaibhavkumar**

### CODE REVIEW

**Comment by manan-shxrma** [comment]
binary search has already been added. Try adding an algorithm that has not yet been added.

**Comment by ervaibhavkumar** [comment]
@manan-shxrma Binary search in Python doesn't exist but in C and Cpp only. Kindly re-review the pull request. Thanks

**Comment by manan-shxrma** [comment]
PR's coded in any other language other than c/c++ are now not being accepted. Moreover, try adding an algorithm that has not yet been added. Thanks

**Comment by ervaibhavkumar** [comment]
Got that. Will push the other algo. 
But this thing is not mentioned in the guidelines related to c/c++. I would appreciate if you could remove the "spam" label.
Thanks

**Comment by manan-shxrma** [comment]
sure, I will remove the label.

**Comment by ervaibhavkumar** [comment]
> sure, I will remove the label.

Thanks :)

**Pull request closed without merging**
