### PR TITLE
Create InfixToPrefix.cpp

### PR DESCRIPTION
**Pull request by anant0070**

### CODE REVIEW

**Comment by manan-shxrma** [comment]
provide a detailed description of your commit

**Comment by anant0070** [comment]
do i need to add explanation? or the steps ?

**Comment by manan-shxrma** [comment]
image
you need to add some description of your commit, do not leave it blank

**Comment by anant0070** [comment]
ok

**Comment by anant0070** [comment]
Screenshot (444)
I am unable to commit changes now, can u help

**Comment by anant0070** [comment]
Done

**Pull request merged**
