### PR TITLE
Added Heap sort in C language

### PR DESCRIPTION
**Pull request by SrishtiSingh-hub**

### CODE REVIEW

**Comment by manan-shxrma** [comment]
heap sort is already covered in c++. Moreover, PR's coded in c are now not being merged.

**Comment by SrishtiSingh-hub** [comment]
Can you please let me know why you have tagged me as spam?

**Comment by SrishtiSingh-hub** [comment]
Please remove the spam label.

**Comment by SrishtiSingh-hub** [comment]
@manan-shxrma remove the spam label

**Pull request closed without merging**
