### PR TITLE
Reverse a string using stacks 

### PR DESCRIPTION
**Pull request by shrishail356**
Hi guys here is a programme to print the reverse of a string using stacks concept in data structures and algorithms
the code is written in c++ , you can also do the same in any language you like referring to the concept in the code 
Thank you!

### CODE REVIEW

**Comment by shrishail356** [comment]
Screenshot 2022-10-11 210510

plz add the lable as in the scrrenshot so as to get approved for hacktoberfest

**Comment by shrishail356** [comment]
hacktoberfest-accepted lable not hacktoberfest lable

**Comment by manan-shxrma** [comment]
FYI if a repo has the label of hacktoberfest, then any PR accepted since that label is put, automatically getsaccepted under hacktoberfest

**Comment by manan-shxrma** [comment]
image
.
.
add a description of your commit

**Comment by manan-shxrma** [comment]
i am reopening it again, edit your commit and ping me again

**Comment by shrishail356** [comment]
@manan-shxrma done with the description

**Comment by shrishail356** [comment]
thank you🙏

**Pull request merged**
