### PR TITLE
Adding code to check if two arrays are equal or not in Cpp

### PR DESCRIPTION
**Pull request by ervaibhavkumar**
Dear Maintainer,

The repository doesn't have the logic to check whether two arrays are equal using cpp and hence pushing this change. let me know on this

Thanks and Regards
Vaibhav

### CODE REVIEW

**Review by manan-shxrma — CHANGES_REQUESTED** [review]
This is not a hashing algorithm so kindly add it to the requisite folder.

**Comment by ervaibhavkumar** [comment]
@manan-shxrma Can you suggest an appropriate folder or shall I just create a folder with the name "Arrays" or "Miscellaneous" ?
Thanks

**Comment by manan-shxrma** [comment]
I feel miscellaneous would work well.

**Comment by ervaibhavkumar** [comment]
Thanks @manan-shxrma . I have promoted the changes. let me know

**Comment by manan-shxrma** [comment]
great!

**Review by manan-shxrma — APPROVED** [review]
great work mate!

**Comment by ervaibhavkumar** [comment]
> great work mate!

Thanks for the support. Would also appreciate if you can add the hacktoberfest-accepted label if required for this. 
Cheers!!

**Pull request merged**
