### PR TITLE
Create insertion_in_LL.cpp

### PR DESCRIPTION
**Pull request by VINAYBOYAT11**

### CODE REVIEW

**Comment by VINAYBOYAT11** [comment]
@manan-shxrma  please check out my request

**Review by manan-shxrma — COMMENTED** [review]
insertion and deletion are already completed under the linked list, kindly verify the request and then make a PR.

**Comment by VINAYBOYAT11** [comment]
i amke sure i uplode right code in this repo .. please can you remove this spam tag ..
i am  working  hard for hacktober fest ... this spam waring is so terrifing..
am requesting you to please remove this code...

**Comment by VINAYBOYAT11** [comment]
hey maan i upolded the right files in your repo can you please check out..

**Comment by manan-shxrma** [comment]
> i make sure i uplode right code in this repo .. please can you remove this spam tag .. i am working hard for hacktober fest ... this spam waring is so terrifing.. am requesting you to please remove this tag

okayy but be very careful and particular before before uploading

**Pull request closed without merging**
